### ISSUE TITLE
Can we import DOM by x2js itself?

### ISSUE THREAD

**Issue by ouliuquan** [Axinom/x2js#132]
Hi, I use the repo and I import the "DOM" in tsconfig. My project uses the global.setTimeout at same time. This will cause the window.setTimeout(by DOM) and global.setTimeout(by NodeJS) conflict.
So, can I use the global.setTimeout, and x2js use the Document itself only? In that cause I don't need the write "DOM" in tsconfig.
Thank you for your help.
This is the log:
```
$ tsc -p ./
node_modules/x2js/x2js.d.ts:56:27 - error TS2304: Cannot find name 'Document'.

56     xml2dom(xml: string): Document;
                             ~~~~~~~~

node_modules/x2js/x2js.d.ts:68:24 - error TS2304: Cannot find name 'Document'.

68     dom2js<T>(domNode: Document | Node): T;
                          ~~~~~~~~

node_modules/x2js/x2js.d.ts:68:35 - error TS2304: Cannot find name 'Node'.

68     dom2js<T>(domNode: Document | Node): T;
                                     ~~~~

node_modules/x2js/x2js.d.ts:79:29 - error TS2304: Cannot find name 'Document'.

79     js2dom<T>(jsObject: T): Document;
                               ~~~~~~~~
```

**Comment by ouliuquan** [comment]
"window.setTimeout(by DOM) and global.setTimeout(by NodeJS) conflicted" is too hard to solved, my projcet is TypeScript, forked from [em-ide](https://github.com/github0null/eide), hope you can help me in this problem.

**Comment by Maxouhell** [comment]
Hi, do you have a running example ?
It would help, and save me time trying to reproduct this error

**Comment by ouliuquan** [comment]
@Maxouhell Wait a minutes, I create a repo now.

**Comment by ouliuquan** [comment]
@Maxouhell Hi, I have been upload my env to my [repo](https://github.com/ouliuquan/eide), this project use the nodejs 14.
use the `"x2js": "3.4.1"` will less error, if this work you can use this older version.
step:
`yarn`
`yarn compile`

**Comment by ouliuquan** [comment]
This problem I have found a way to solved, by
```
import { clearTimeout, setTimeout } from 'timers';
```
https://stackoverflow.com/a/58721415,
Thank you for you help again. @Maxouhell
