### ISSUE TITLE
Clarification needed on "conversion is not necessarily lossless"

### ISSUE THREAD

**Issue by romgrk** [Axinom/x2js#49]
From the `readme.md`:
```
The conversion is not necessarily lossless but it is very convenient.
```

Is it possible to elaborate on that? In which cases is it losing data?

**Comment by sandersaares** [comment]
Nobody has compiled such a list, to my knowledge. Things that pop into mind are:

* XML comments do not survive XML->JS->XML conversion.
* CDATA content is converted to plain text content if it is the only child of an element (setting dependent).

There are likely more such aspects and, potentially, places where data is ignored or converted undesirably. However, to my knowledge, nobody has done any investigation of the exact limitations of the library. I would be interested to hear of any experiences you may have on this topic, so it can be better documented!

**Comment by romgrk** [comment]
The one I was mainly concerned was the order of children nodes.
Eg, the readme uses the example:
```js
console.log(document.MyRootElement.ElementX[1].toString());
```

This means that the objects are represented as:
```js
MyRootElement = {
  ElementX: [ /* ... */ ]
}
```

But that the following:
```xml
<MyRootElement>
  <ElementX/>
  <NotElementX/>
  <ElementX/>
</MyRootElement>
```
Looses the ordering.

**Comment by sandersaares** [comment]
Yes, indeed - that is also a good example of this factor.

**Comment by sandersaares** [comment]
Closing this. Please reopen if you have further questions or requests on the topic.

**Comment by mellis481** [comment]
@sandersaares 
> * CDATA content is converted to plain text content if it is the only child of an element (setting dependent).

Is this something that is configurable? I need to retain the CDATA code within an element even if it's the only child.
