### ISSUE TITLE
Installing x2js with npm

### ISSUE THREAD

**Issue by Jacks50** [Axinom/x2js#54]
I'm installing x2js with the npm command `npm install x2js`, but I don't know why the contents are different. Even when installing using the url instead of the module name, I don't have (for example) the same `package.json`, nor the type definition interface (`x2js.d.ts.)`. Is there a reason for it ?

**Comment by sandersaares** [comment]
It may be that you are looking in the development branch of the codebase, which may contain changes that are not yet published to npm. Can you confirm whether the state you see when installing via npm matches the state of the master branch in GitHub?

You can expect the latest changes currently in the development branch to be pushed to npm in December.

**Comment by Jacks50** [comment]
After looking at the state it seems you are right. The branch used is the master by comparing the files it contains. Should I wait until your next push before going further with x2js in my project or can I download and work with the type definition interface from DefinitelyTyped ?

Thank you very much for your answer !

**Comment by sandersaares** [comment]
Feel free to work with the contents of the development branch. There are no open issues, so to the best of my knowledge it is in a good state. I do not currently expect any more changes to take place before it is published to npm - the delay is merely a matter of scheduling.

**Comment by Jacks50** [comment]
Okay, thank you very much for your answers @sandersaares !
