### ISSUE TITLE
js2xml and CDATA

### ISSUE THREAD

**Issue by dragma** [Axinom/x2js#56]
Hi everyone.

I can't handle CDATA insertion on my js formated object using js2xml.

Here is a piece of code i tried :
```javascript
import x2js from 'x2js';
[...]
const parser = new x2js();
const jsonData = {};
jsonData.items = {};
jsonData.items.item = [];

const someValue = 'hello world';

jsonData.items.item.push({
  someKey: `<![CDATA[${someValue}]]>`,
})

console.log(parser.js2xml(jsonData);)
```
(code can be executed here : https://runkit.com/5857a3ffdd1b580013a9d722/5857a3ffdd1b580013a9d723)

Here is the output : `"<items><item><someKey>&lt;![CDATA[hello world]]&gt;</someKey></item></items>"`

How can I get rid of `&lt;![CDATA[` and `]]&gt;` and place the legit `<![CDATA[` ans `]]>` ?

Regards,

Florent

**Comment by sandersaares** [comment]
As far as I know, the library does not have a feature that enables you to accomplish this. All emitted values are XML-escaped, which should eliminate any need for CDATA.

Is there some particular reason you desire to use CDATA instead of normal XML-escaping (given that they are just alternatives to each other)?

**Comment by dragma** [comment]
Hi. 
Back from the dead :)
I don't remember well how I managed to resolve this, but to answer your question, the reasons I desired to use CDATA instead of normal XML-escaping, was purely a business request, impacting though the developpement process.

Regards,
Flo

**Comment by FroggerHH** [comment]
Put your data in a __cdata field. Plain content, the surrounding cdata-tag is being added by x2js.
var myTitle = 'The brown fox';
var myDescription = 'The quick brown fox jumps over the lazy cat.";
let data = {
    title: myTitle,
    description:  [{__cdata : myDescription}],
};
will result in
    <data>
        <title>The brown fox</title>
        <description><![CDATA[The quick brown fox jumps over the lazy cat.]]></description>
    </data>
