### ISSUE TITLE
ELEMENT_NODEs takes precedence over TEXT_NODEs while converting back to XML 

### ISSUE THREAD

**Issue by itskdk** [Axinom/x2js#58]
Hi,

I am attempting to parse **[XLIFF 1.2 Sample File](http://docs.oasis-open.org/xliff/v1.2/cs02/Sample_AlmostEverything_1.2_transitional.xlf)** using this module. 

This module is very much suitable for my requirements as it is lightweight as well as works both in client (browser) and server (node) environments.

I recently came across this issue while experimenting with it and wanted to report the same. 
The details are as follows: -

> Conversion from **XML->JS** is working as expected, but one thing, I noticed upon converting from **JS->XML**, _the **order/positions of TEXT_NODES** inside **&lt;source&gt;** or **&lt;target&gt;** tags (both belongs to XLIFF) gets disturb; the nearby XLIFF Elements takes precedence over these TEXT_NODES._

**Just wanted to check with you, is it the right behavior? OR I am missing some configuration.**  

For better clarity, please use the following links: -

- **The reported issue can be reproduced from this RunKit [link](https://runkit.com/5886e54c4891470013ec3365/588728f01e26bf001359b11f).**

- **The ORIGINAL and GENERATED XML outcomes can be checked via Diff Checker [link](https://www.diffchecker.com/2wZ7GxDW).**

Hope it helps you to understand the discussed problem in this use-case.
Kindly suggest a suitable fix for this issue.

**Comment by sandersaares** [comment]
Yes, this does appear to be a limitation of the library. The transformation is not order-preserving.

In theory, I suppose the library could be augmented to support this but I wonder if the magnitude of such a change might be outside the scope of a simple and easy to use library. Preserving order might not be very practical in terms of accurately reflecting modifications of the XML tree (how do you insert?) and so forth.

I would therefore consider this out of scope of the library. I suggest you find a SAX-style reader/writer library where the exact order and structure of XML is important to you.

**Comment by itskdk** [comment]
Thanks for the reply. 
In my use-case, order of these nodes is very important. 
Hence as suggested by you would look for other/similar options.

Have a great day!!!
