### ISSUE TITLE
require('x2js') return nothing

### ISSUE THREAD

**Issue by rgfactory** [Axinom/x2js#59]
Hello,

I would like to use your x2js module in my angularjs Ionic app thanks to browserify.

So I installed it with : npm i -S x2js.

But I do : 
`var x2js = require('x2js');
console.log(x2js);`

that display an empty object in the javascript console : 
`{}`

What am I doing wrong ?

FYI I did the exact same thing with the [underscore](https://www.npmjs.com/package/underscore) module in the same file, and it worked.

Thank you in advance :)

**Comment by sandersaares** [comment]
The library uses the UMD pattern, specifically the [returnExports variant](https://github.com/umdjs/umd/blob/master/templates/returnExports.js). It should work in all common cases as UMD is an industry standard pattern.

I am not experienced in the integration scenario you have, so I am afraid I cannot provide any detailed assistance with integration into your specific project.
